In [1]:
## First step is to import pandas

import pandas as pd
import numpy as np

In [2]:
## Playing with Dataframe

df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Coumn4"])

In [3]:
df.head()

      Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [4]:
## Accessing the elements

df.loc['Row1']

Column1    0
Column2    1
Column3    2
Coumn4     3
Name: Row1, dtype: int64

In [5]:
## Check the type

type(df.loc['Row1'])

pandas.core.series.Series

In [6]:
df.iloc[:,:]

      Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [7]:
## Take the elements from the Column2
df.iloc[:,1:]

      Column2  Column3  Coumn4
Row1        1        2       3
Row2        5        6       7
Row3        9       10      11
Row4       13       14      15
Row5       17       18      19

In [8]:
#convert Dataframes into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [9]:
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [10]:
df=pd.read_csv('mercedesbenz.csv')

In [11]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [13]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
#Get the unique category counts
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
aq     18
i      18
am     18
u      17
aw     16
l      16
ad     14
k      11
au     11
b      11
r      10
as     10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [15]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [16]:
df.corr(numeric_only=True)

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,1.000000,-0.055108,0.001602,NaN,0.058988,-0.031917,-0.025438,0.002237,-0.036480,-0.038171,...,0.045229,-0.080259,-0.022965,0.030371,0.023382,-0.013577,-0.038171,-0.009332,-0.015355,0.029059
y,-0.055108,1.000000,-0.026985,NaN,0.089792,0.048276,0.193643,0.023116,0.048946,-0.159815,...,0.029100,0.114005,0.061403,-0.258679,0.067919,0.040932,-0.159815,0.040291,-0.004591,-0.022280
X10,0.001602,-0.026985,1.000000,NaN,-0.033084,-0.028806,-0.100474,-0.002532,-0.005944,-0.010164,...,0.165277,-0.028618,-0.074244,-0.016870,-0.011374,-0.010479,-0.010164,-0.004740,-0.002532,-0.004387
X11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
X12,0.058988,0.089792,-0.033084,NaN,1.000000,0.214825,-0.246513,-0.006212,-0.014584,-0.024937,...,-0.107864,-0.070214,0.030134,-0.016043,-0.027907,-0.005566,-0.024937,-0.011628,-0.006212,-0.010765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
X380,-0.013577,0.040932,-0.010479,NaN,-0.005566,0.023045,0.007743,-0.001968,-0.004619,-0.007899,...,-0.061741,-0.022240,-0.061168,-0.013110,-0.008839,1.000000,-0.007899,-0.003683,-0.001968,-0.003410
X382,-0.038171,-0.159815,-0.010164,NaN,-0.024937,-0.021713,0.012713,-0.001908,-0.004480,1.000000,...,-0.059883,-0.021571,-0.059327,-0.012716,-0.008573,-0.007899,1.000000,-0.003572,-0.001908,-0.003307
X383,-0.009332,0.040291,-0.004740,NaN,-0.011628,-0.010125,0.023604,-0.000890,-0.002089,-0.003572,...,-0.015413,-0.010059,0.035107,-0.005930,-0.003998,-0.003683,-0.003572,1.000000,-0.000890,-0.001542
X384,-0.015355,-0.004591,-0.002532,NaN,-0.006212,0.041242,0.025199,-0.000475,-0.001116,-0.001908,...,-0.014917,-0.005373,0.008694,-0.003168,-0.002136,-0.001968,-0.001908,-0.000890,1.000000,-0.000824
X385,0.029059,-0.022280,-0.004387,NaN,-0.010765,-0.009373,0.043667,-0.000824,-0.001934,-0.003307,...,0.055225,-0.009311,-0.025610,-0.005489,-0.003701,-0.003410,-0.003307,-0.001542,-0.000824,1.000000

In [17]:
df['X11'].value_counts()

X11
0    4209
Name: count, dtype: int64

In [18]:
import numpy as np

In [19]:
lst_data=[[1,2,3],[3,4,np.nan],[5,6,np.nan],[np.nan,np.nan,np.nan]]

In [20]:
df=pd.DataFrame(lst_data)

In [21]:
df.head()

     0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN
2  5.0  6.0  NaN
3  NaN  NaN  NaN

In [22]:
## Handling Missing Values
## Drop nan values
df.dropna(axis=0)

     0    1    2
0  1.0  2.0  3.0

In [23]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [24]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'],
                     columns=['one', 'two', 'three'])

In [25]:
df.head()

        one       two     three
a  0.360576  1.828551 -0.500078
c  0.027896  1.162850 -0.489742
e -0.834477  0.357556 -0.355123
f  0.825240 -0.271534  2.202159
h  0.383379  0.724539 -0.838594

In [26]:
df2=df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [27]:
df2

        one       two     three
a  0.360576  1.828551 -0.500078
b       NaN       NaN       NaN
c  0.027896  1.162850 -0.489742
d       NaN       NaN       NaN
e -0.834477  0.357556 -0.355123
f  0.825240 -0.271534  2.202159
g       NaN       NaN       NaN
h  0.383379  0.724539 -0.838594

In [28]:
df2.dropna(axis=0)

        one       two     three
a  0.360576  1.828551 -0.500078
c  0.027896  1.162850 -0.489742
e -0.834477  0.357556 -0.355123
f  0.825240 -0.271534  2.202159
h  0.383379  0.724539 -0.838594

In [29]:
pd.isna(df2['one'])

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [30]:
df2['one'].notna()

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: one, dtype: bool

In [31]:
df2.fillna('Missing')

        one       two     three
a  0.360576  1.828551 -0.500078
b   Missing   Missing   Missing
c  0.027896   1.16285 -0.489742
d   Missing   Missing   Missing
e -0.834477  0.357556 -0.355123
f   0.82524 -0.271534  2.202159
g   Missing   Missing   Missing
h  0.383379  0.724539 -0.838594

In [32]:
df2['one'].values

array([ 0.36057551,         nan,  0.02789606,         nan, -0.83447717,
        0.82524046,         nan,  0.38337898])

In [33]:
from io import StringIO, BytesIO

In [34]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [35]:
type(data)

str

In [36]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [37]:
## Read from specific columns
df=pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ['COL1', 'COL3'])

In [38]:
df.to_csv('Test.csv')

In [39]:
## Specifying columns data types

data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [40]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [41]:
df=pd.read_csv(StringIO(data),dtype=object)

In [42]:
df

   a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [43]:
df['a'][1]

'5'

In [44]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':'Int64'})

In [45]:
df

   a   b     c    d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN

In [46]:
df['a'][1]

np.int64(5)

In [47]:
## check the datatype
df.dtypes

a      Int64
b      int64
c    float64
d    float64
dtype: object

In [48]:
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [49]:
pd.read_csv(StringIO(data),index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [50]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')

In [51]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [52]:
pd.read_csv(StringIO(data),index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [53]:
## Combining usecols and index_col
data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')

In [54]:
pd.read_csv(StringIO(data), usecols=['b', 'c'],index_col=False)

        b    c
0   apple  bat
1  orange  cow

In [55]:
## Quoting and Escape Characters¶. Very useful in NLP

data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [56]:
pd.read_csv(StringIO(data),escapechar='\\')

                               a  b
0  hello, "Bob", nice to see you  5

In [59]:
## URL to CSV
## Note: download.bls.gov blocks automated/bot requests (Akamai), so fetching
## the file directly with pd.read_csv(url) returns a 403. Download it once
## from a browser and save it as 'cu.item.txt' next to this notebook instead.

df=pd.read_csv('F:\Modern-Route-Full-Stack-GenerativeAI-And-Agentic-AI-Bootcamp\Python Crash Course\cu.item.txt', sep='\t')

In [60]:
df.head()

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359

In [61]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(Data)

C:\Users\USER\AppData\Local\Temp\ipykernel_24676\73091601.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(Data)

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [62]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [63]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [64]:
df.to_csv('wine.csv')